name: htmldoc
base: core20
version: 1.9.12
summary: HTML and Markdown conversion utility
description: |
  HTMLDOC is a program that reads HTML and Markdown source files or web pages
  and generates corresponding EPUB, HTML, PostScript, or PDF files with an
  optional table of contents.

#confinement: devmode
confinement: strict

#grade: devel
grade: stable

icon: desktop/htmldoc-128.png

apps:
    htmldoc:
        command: desktop-launch $SNAP/bin/htmldoc
        desktop: share/applications/htmldoc.desktop
        plugs: [desktop, home, network, x11]

parts:
    main:
        plugin: autotools
        source: .

build-packages: [libfltk1.3-dev, libgnutls28-dev, libjpeg8-dev, libpng16-dev, zlib1g-dev]
